const embeddedYasalData = [
  {
    "id": "1",
    "kanunNo": "2804",
    "kabulTarihi": "14.06.1935",
    "baslik": "Maden Tetkik ve Arama Enstitüsü Genel Müdürlüğü Kanunu",
    "rgTarih": "22.06.1935",
    "rgSayi": "3035",
    "amac": "Hükmî şahsiyeti haiz olmak ve bütün muamelelerinde bu kanun ile hukuku hususiye ahkâmına tâbi bulunmak üzere Ânkarada bir M . T. A . Enstitüsü, (Maden Tetkik ve Arama Enstitüsü) kurulmuştur. M.T.A. Enstitüsü ticarî usullere göre idare olunur. Bu enstitünün bütün sarfiyat ve muamelâtı, muhasebei umumiye, artırma, eksiltme ve ihale kanunlarına ve Divanı Muhasebatın vize ve murakabesine tâbi değildir.",
    "category": "Yasal Düzenlemeler",
    "erisimLinki": "https://www.resmigazete.gov.tr/kanun-2804"
  },
  {
    "id": "2",
    "kanunNo": "2805",
    "kabulTarihi": "14.06.1935",
    "baslik": "Etibank Kanunu",
    "rgTarih": "22.06.1935",
    "rgSayi": "3035",
    "amac": "Hükmî şahsiyeti haiz olmak ve bu kanun ile hukuku hususiye ahkâmına tâbi bulunmak üzere Ankara'da \\\\\\\\\\\\\"Etibank\\\\\\\\\\\\\" kurulmuştur. Bu banka İtktısad Vekâletinin müsaadesile başka yerlerde şubeler açabilir. Etibank, ticarî usullere göre idare olunur ve muhasebei umumiye, arttırma, eksiltme ve ihale kanunları ile Divanı Muhasebatın vize ve murakabesine tâbi değildir.",
    "category": "Yasal Düzenlemeler",
    "erisimLinki": "https://www.tbmm.gov.tr/kanunlar/kanun-2805"
  },
  {
    "id": "3",
    "kanunNo": "3645",
    "kabulTarihi": "16.06.1939",
    "baslik": "İstanbul Elektrik, Tramvay ve Tünel İdareleri Teşkilât Ve Tesisatının İstanbul Belediyesine Devrine Dair Kanun",
    "rgTarih": "22.06.1939",
    "rgSayi": "4239",
    "amac": "İstanbul Elektrik, Tramvay ve Tünel Şirketlerinin satın alınmasına dair mukavelenamelerin tasdiki hakkındaki kanunlarla bu kanunlara bağlı mukavelenameler mucibince Hükümete intikal eden haklar ve vecibeler ve bilcümle tesisat ve mezkûr kanunlarla vücuda getirilmiş olan teşekküller bütün halk, salâhiyet ve vecibelerile İstanbul Belediyesine devredilmiştir.",
    "category": "Yasal Düzenlemeler",
    "erisimLinki": "https://www.mevzuat.gov.tr/kanun-3645"
  },
  {
    "id": "4",
    "kanunNo": "3867",
    "kabulTarihi": "30.05.1940",
    "baslik": "Ereğli Kömür Havzasındaki Ocakların Devletçe İşlettirilmesi Hakkında Kanun",
    "rgTarih": "05.06.1940",
    "rgSayi": "4527",
    "amac": "Ereğli kömür havzası dahilindeki kömür ocaklarının tamamının veya bir kısmının Devletçe işlettirilmesine karar vermeğe icra Vekilleri Heyeti salahiyetlidir. Bu ocakların Devletçe işlettirilmesi zamanı bir defaya mahsus olmak üzere kararname ile tesbit ve ilân olunur.",
    "category": "Yasal Düzenlemeler",
    "erisimLinki": "https://kutuphane.tarimorman.gov.tr/kanun-3867"
  },
  {
    "id": "5",
    "kanunNo": "4325",
    "kabulTarihi": "16.12.1942",
    "baslik": "Ankara Elektrik ve Havagazı ve Adana Elektrik Müesseselerinin İdare ve İşletmeleri Hakkında Kanun",
    "rgTarih": "26.12.1942",
    "rgSayi": "5290",
    "amac": "Ankara Elektrik ve Havagazı ve Adana Elektrik hizmetlerini görmek üzere bu şehirler belediyelerince (Ankara Elektrik ve Havagazı İşleltane Müessesesi) ve (Adana Elektrik İşletme Müessesesi) adlariyle birer müessese kurulur. Bu müesseseler, hükmî şahsiyeti haiz olmak ve adı geçen belediyelere bağlı bulunmak üzere birer umum müdürlük veya müdürlük tarafından bu kanunda yazılı esaslara ve hususi hukuk hükümlerine göre idare edilir.",
    "category": "Yasal Düzenlemeler",
    "erisimLinki": "https://kutuphane.sbb.gov.tr/kanun-4325"
  },
  {
    "id": "6",
    "kanunNo": "4483",
    "kabulTarihi": "19.07.1943",
    "baslik": "İzmir Tramvay ve Elektrik Türk Anonim Şirketi İmtiyaziyle Tesisatının Satın Alınmasına Dair Mukavelenin Tasdiki Ve Bu Müessesenin İşletilmesi Hakkında Kanun",
    "rgTarih": "27.07.1943",
    "rgSayi": "5466",
    "amac": "İzmir Tramvay ve Elektrik Türk Anonim Şirketi imtiyaz ve tesisatının satın alınmasına dair 24/6/1943 tarihinde Nafıa Vekili ile salahiyetli Şirket murahhası arasında imza ve teati edilmiş olan bağlı mukavelename tasdik edilmiştir.",
    "category": "Yasal Düzenlemeler",
    "erisimLinki": "https://www.resmigazete.gov.tr/kanun-4483"
  },
  {
    "id": "7",
    "kanunNo": "4762",
    "kabulTarihi": "20.06.1945",
    "baslik": "İstanbul Havagazı Ve Elektrik Ve Teşebbüsatı Sınaiye Türk Anonim Şirketi\\\\\\\\\\\\\" vi Satın Alma Sözleşmesinin Onanmasına ve \\\\\\\\\\\\\"İstanbul Elektrik, Tramvay Ve Tünel İşletmeleri İdaresi\\\\\\\\\\\\\" Ne Devrine Dair Kanun",
    "rgTarih": "28.06.1945",
    "rgSayi": "6043",
    "amac": "«İstanbul Havagazı ve Elektrik ve Teşebbüsatı Sınaiye Türk Anonim Şirketi» imtiyaz ve tesislerinin satın alınmasına dair 23 Kasım 1944 de Hükümet, istanbul Belediyesi ve Ortaklık temsilcileri arasında imza edilmiş olan bağlı sözleşme ve ekleri onanmış ve Ortaklık elindeki imtiyaz kaldırılmıştır.",
    "category": "Yasal Düzenlemeler",
    "erisimLinki": "https://www.tbmm.gov.tr/kanunlar/kanun-4762"
  },
  {
    "id": "8",
    "kanunNo": "2690",
    "kabulTarihi": "07.09.1982",
    "baslik": "Türkiye Atom Enerjisi Kurumunun Muafiyetleri Ve Bazı Düzenlemeler Yapılması Hakkında Kanun",
    "rgTarih": "13.07.1982",
    "rgSayi": "17753",
    "amac": "Barışçıl amaçlarla Türkiye'de atom enerjisinin kalkınma planlarına uygun olarak ülke yararına kullanılmasını sağlamak, temel ilke ve politikaları belirleyip önermek, bilimsel, teknik ve idari çalışmaları yapmak, düzenlemek, desteklemek, koordine etmek ve denetlemek üzere Türkiye Atom Enerjisi Kurumunun kuruluşu, işleyişi, görev, yetki ve sorumluluklarını saptamaktır.",
    "category": "Yasal Düzenlemeler",
    "erisimLinki": "https://www.mevzuat.gov.tr/kanun-2690"
  },
  {
    "id": "9",
    "kanunNo": "2705",
    "kabulTarihi": "09.09.1982",
    "baslik": "1312 Sayılı Türkiye Elektrik Kurumu Kanununun Bazı Maddelerinin Değiştirilmesi, İki Maddesinin Yürürlükten Kaldırılması, Bazı Madde, Bent Ve Fıkra Eklenmesi Hakkında Kanun",
    "rgTarih": "11.09.1982",
    "rgSayi": "17809",
    "amac": "1312 sayılı Türkiye Elektrik Kurumu Kanununun 3 üncü maddesinin 2 nci fıkrası ve (e) bendi aşağıdaki şekilde değiştirilmiş ve maddeye aşağıdaki (i) bendi eklenmiştir. Bu Kanunda yazılı istisnalar dışında, yurdun ihtiyacı bulunan elektriğin üretim, iletim, dağıtım ve ticaretini yapmak. Bu amaçla; e) Köy elektriklendirme fonunu yönetmek. i) 16.6.1939 tarih ve 3645 sayılı Kanunla kurulan İstanbul Elektrik, Tramvay ve Tünel İşletmeleri Umum Müdürlüğünün, 16.12.1942 tarih ve 4325 sayılı Kanunla kurulan Ankara Elektrik ve Havagazı İşletme Müessesesinin ve aynı Kanunla kurulan Adana Elektrik İşletme Müessesesinin, 19.7.1943 tarih ve 4483 sayılı Kanunla kurulan müessesenin, belediye ve köylerle bunların birliklerinin ve elektrik hizmeti için kurulmuş diğer birliklerin elektrik hizmetlerine ilişkin tesis ve işi etmelerini devralmak ve işletmek.",
    "category": "Yasal Düzenlemeler",
    "erisimLinki": "https://kutuphane.tarimorman.gov.tr/kanun-2705"
  },
  {
    "id": "10",
    "kanunNo": "2840",
    "kabulTarihi": "06.10.1983",
    "baslik": "Bor Tuzları, Trona Ve Asfaltit Madenleri İle Nükleer Enerji Hammaddelerinin İşletilmesini,Linyit Ve Demir Sahalarının Bazılarının İadesini Düzenleyen Kanun",
    "rgTarih": "13.06.1983",
    "rgSayi": "18076",
    "amac": "Bu Kanunun amacı; «2172 sayılı Devletçe İşletilecek Madenler Hakkında Kanun»la kamu kuruluşlarına devredilen maden haklarını yeniden düzenlemektir. Devlet eliyle işletilecek madenler",
    "category": "Yasal Düzenlemeler",
    "erisimLinki": "https://kutuphane.sbb.gov.tr/kanun-2840"
  },
  {
    "id": "11",
    "kanunNo": "2872",
    "kabulTarihi": "1983-08-09 00:00:00",
    "baslik": "Çevre Kanunu",
    "rgTarih": "1983-08-11 00:00:00",
    "rgSayi": "18132",
    "amac": "Bu Kanunun amacı, bütün canlıların ortak varlığı olan çevrenin, sürdürülebilir çevre ve sürdürülebilir kalkınma ilkeleri doğrultusunda korunmasını sağlamaktır.",
    "category": "Yasal Düzenlemeler",
    "erisimLinki": "https://www.resmigazete.gov.tr/kanun-2872"
  },
  {
    "id": "12",
    "kanunNo": "3096",
    "kabulTarihi": "12.04.1984",
    "baslik": "Türkiye Elektrik Kurumu Dışındaki Kuruluşların Elektrik Üretimi, İletimi, Dağıtımı Ve Ticareti İle Görevlendirilmesi Hakkında Kanun",
    "rgTarih": "19.12.1984",
    "rgSayi": "18610",
    "amac": "B u Kanunun amacı, Türkiye Elektrik Kurumu dışındaki özel hukuk hükümlerine tabi sermaye şirketleri statüsüne sahip yerli ve yabancı şirketler in elektrik üretimi, iletimi, dağıtımı ve ticareti ile görevlendirilmesini düzenlemektir.",
    "category": "Yasal Düzenlemeler",
    "erisimLinki": "https://www.tbmm.gov.tr/kanunlar/kanun-3096"
  },
  {
    "id": "13",
    "kanunNo": "3303",
    "kabulTarihi": "06.05.1986",
    "baslik": "Taşkömürü Havzasındaki Taşınmaz Malların İktisabına Dair Kanun",
    "rgTarih": "19.06.1986",
    "rgSayi": "19139",
    "amac": "Bu Kanunun amacı, 17 Ocak 1326 (1910) tarih ve 289 sayılı Tezkere-i Samiyye ile hudutları belirlenen ve 5.2.1958 tarih ve 4/9925 sayılı Bakanlar Kurulu Kararıyla hudutları genişletilen taşkömürü havzası dahilinde,taşınmaz malların .zilyetleri adına tesciline imkân sağlamaktır.",
    "category": "Yasal Düzenlemeler",
    "erisimLinki": "https://www.mevzuat.gov.tr/kanun-3303"
  },
  {
    "id": "14",
    "kanunNo": "4283",
    "kabulTarihi": "16.07.1997",
    "baslik": "Yap-İşlet Modeli İle Elektrik Enerjisi Üretim Tesislerinin Kurulması Ve İşletilmesi İle Enerji Satışının Düzenlenmesi Hakkında Kanun",
    "rgTarih": "19.07.1997",
    "rgSayi": "23054",
    "amac": "Bu Kanunun amacı; \\\\\\\\\\\\\"Yap-İşlet Modeli\\\\\\\\\\\\\" ile üretim şirketlerine ülke enerji plan ve politikalarına uygun biçimde elektrik enerjisi üretmek için mülkiyetleri kendilerine ait olmak üzere termik santral kurma ve işletme izni verilmesi ile enerji satışına dair esas ve usulleri belirlemektir Hidroelektrik, jeotermal, nükleer santrallar ve diğer yenilenebilir enerji kaynakları ile çalıştırılacak santrallar bu Kanunun kapsamı dışındadır",
    "category": "Yasal Düzenlemeler",
    "erisimLinki": "https://kutuphane.tarimorman.gov.tr/kanun-4283"
  },
  {
    "id": "15",
    "kanunNo": "4519",
    "kabulTarihi": "02.01.2000",
    "baslik": "Avrupa Enerji Şartı Anlaşmasının Onaylanmasının Uygun Bulunduğuna Dair Kanun",
    "rgTarih": "07.12.2000",
    "rgSayi": "24107",
    "amac": "Türkiye Cumhuriyeti Hükümeti adına 17 Aralık 1994 tarihinde Lizbon'da imzalanan Avrupa Enerji Şartı Konferansı Nihai Senedi, Enerji Şartı Antlaşması ve ekini teşkil eden kararlar ile Enerji Verimliliğine ve İlgili Çevresel Hususlara İlişkin Enerji Şartı Protokolü'nün onaylanması uygun bulunmuştur",
    "category": "Yasal Düzenlemeler",
    "erisimLinki": "https://kutuphane.sbb.gov.tr/kanun-4519"
  },
  {
    "id": "16",
    "kanunNo": "4586",
    "kabulTarihi": "23.06.2000",
    "baslik": "Petrolün Boru Hatları İle Transit Geçişine Dair Kanun",
    "rgTarih": "29.06.2000",
    "rgSayi": "24094",
    "amac": "Bu Kanunun amacı, petrolün boru hatları ile transit geçişine ilişkin usul ve esasları belirlemek ve her bir transit petrol boru hattı projesi ile ilgili Türkiye'nin taraf olduğu milletlerarası andlaşma hükümlerinin uygulanmasını sağlamaktır",
    "category": "Yasal Düzenlemeler",
    "erisimLinki": "https://www.resmigazete.gov.tr/kanun-4586"
  },
  {
    "id": "17",
    "kanunNo": "4628",
    "kabulTarihi": "20.02.2001",
    "baslik": "Enerji Piyasası Düzenleme Kurumunun Teşkilat Ve Görevleri Hakkında Kanun",
    "rgTarih": "03.03.2001",
    "rgSayi": "24335 (Mükerrer)",
    "amac": "Bu Kanunun amacı; elektriğin yeterli, kaliteli, sürekli, düşük maliyetli ve çevreyle uyumlu bir şekilde tüketicilerin kullanımına sunulması için, rekabet ortamında özel hukuk hükümlerine göre faaliyet gösterebilecek, mali açıdan güçlü, istikrarlı ve şeffaf bir elektrik enerjisi piyasasının oluşturulması ve bu piyasada bağımsız bir düzenleme ve denetimin sağlanmasıdır. Bu Kanun; elektrik üretimi, iletimi, dağıtımı, toptan satışı, perakende satışı, perakende satış hizmeti, ithalat ve ihracatı ile bu faaliyetlerle ilişkili tüm gerçek ve tüzel kişilerin hak ve yükümlülüklerini, Elektrik Piyasası Düzenleme Kurumunun kurulması ile çalışma usul ve esaslarını ve elektrik üretim ve dağıtım varlıklarının özelleştirilmesinde izlenecek usulü kapsar.",
    "category": "Yasal Düzenlemeler",
    "erisimLinki": "https://www.tbmm.gov.tr/kanunlar/kanun-4628"
  },
  {
    "id": "18",
    "kanunNo": "4646",
    "kabulTarihi": "18.04.2001",
    "baslik": "Doğal Gaz Piyasası Kanunu (Elektrik Piyasası Kanununda Değişiklik Yapılması Ve Doğal Gaz Piyasası Hakkında Kanun)",
    "rgTarih": "02.05.2001",
    "rgSayi": "24390",
    "amac": "Bu Kanunun amacı; doğal gazın kaliteli, sürekli, ucuz, rekabete dayalı esaslar çerçevesinde çevreye zarar vermeyecek şekilde tüketicilerin kullanımına sunulması için, doğal gaz piyasasının serbesti eştiril erek mali açıdan güçlü, istikrarlı ve şeffaf bir doğal gaz piyasasının oluşturulması ve bu piyasada bağımsız bir düzenleme ve denetimin sağlanmasıdır.",
    "category": "Yasal Düzenlemeler",
    "erisimLinki": "https://www.mevzuat.gov.tr/kanun-4646"
  },
  {
    "id": "19",
    "kanunNo": "4680",
    "kabulTarihi": "13.06.2001",
    "baslik": "Üretimini Likit Petrol Gazı İle Yapan Üreticilerin Zararlarının Karşılanması Hakkında Kanun",
    "rgTarih": "26.06.2001",
    "rgSayi": "24444",
    "amac": "Madde 1. 1.5.2001 ile 31.12.2001 tarihleri arasında üretimlerini likit petrol gazı ile yapan karo seramik, vitrifıye sağlık gereçleri ve porselen sofra eşyası üreticileri ile bu üretim tesislerine likit petrol gazı kullanarak elektrik sağlamak amacıyla kurulan kojeneratör sistemli otoprodüktör tesislerin, yukarıda belirtilen sanayi üretimlerinden kendi üretimlerinde kullandıkları elektrik miktarı için kullandıkları likit petrol gazının maliyeti ile aynı üretimin doğal gaz ile yapılmış olması halinde hesaplanacak maliyet arasındaki farkın % 70'i Enerji ve Tabiî Kaynaklar Bakanlığı bütçesine konulacak ödenekten karşılanır.",
    "category": "Yasal Düzenlemeler",
    "erisimLinki": "https://kutuphane.tarimorman.gov.tr/kanun-4680"
  },
  {
    "id": "20",
    "kanunNo": "5015",
    "kabulTarihi": "12.04.2003",
    "baslik": "Petrol Piyasası Kanunu",
    "rgTarih": "20.12.2003",
    "rgSayi": "25322",
    "amac": "Bu Kanunun amacı; yurt içi ve yurt dışı kaynaklardan temin olunan petrolün doğrudan veya işlenerek güvenli ve ekonomik olarak rekabet ortamı içerisinde kullanıcılara sunumuna ilişkin piyasa faaliyetlerinin şeffaf, eşitlikçi ve istikrarlı biçimde sürdürülmesi için yönlendirme, gözetim ve denetim faaliyetlerinin düzenlenmesini sağlamaktır.",
    "category": "Yasal Düzenlemeler",
    "erisimLinki": "https://kutuphane.sbb.gov.tr/kanun-5015"
  },
  {
    "id": "21",
    "kanunNo": "5307",
    "kabulTarihi": "03.02.2005",
    "baslik": "Sıvılaştırılmış Petrol Gazları (Lpg) Piyasası Kanunu Ve Elektrik Piyasası Kanununda Değişiklik Yapılmasına Dair Kanun",
    "rgTarih": "13.03.2005",
    "rgSayi": "25754",
    "amac": "Bu Kanunun amacı, yurt içi ve yurt dışı kaynaklardan temin olunan sıvılaştırılmış petrol gazlarının güvenli ve ekonomik olarak rekabet ortamı içerisinde kullanıcılara sunumuna ilişkin piyasa faaliyetlerinin şeffaf, eşitlikçi ve istikrarlı biçimde sürdürülmesi için gerekli düzenleme, yönlendirme, gözetim ve denetim faaliyetlerinin yapılmasını sağlamaktır.",
    "category": "Yasal Düzenlemeler",
    "erisimLinki": "https://www.resmigazete.gov.tr/kanun-5307"
  },
  {
    "id": "22",
    "kanunNo": "5312",
    "kabulTarihi": "03.03.2005",
    "baslik": "Deniz Çevresinin Petrol Ve Diğer Zararlı Maddelerle Kirlenmesinde Acil Durumlarda Müdahale Ve Zararların Tazmini Esaslarına Dair Kanun",
    "rgTarih": "11.03.2005",
    "rgSayi": "25752",
    "amac": "Bu Kanunun amacı, deniz emniyetinin sağlanması ve deniz kirliliğinin önlenmesi konusundaki uluslararası hukuk ve iç hukuktan doğan hak ve yükümlülükler göz önünde bulundurularak; a) Acil durumlarda gemilerden ve kıyı tesislerindeki faaliyetlerden kaynaklanan kirlenme tehlikesini ortadan kaldırmak veya kirlenmeyi azaltmak, sınırlamak ve gidermek üzere uygulanacak müdahale ve hazırlıklı olma esaslarını, b) Olay sonucu ortaya çıkan zararların tespit ve tazmin esaslarını, c) Uluslararası yükümlülüklerin yerine getirilmesi esaslarını, d) Kanun kapsamına giren kişilerle kurum, kuruluş, gemi ve tesislerin Kanunda belirtilen ilgililerinin yetki, görev ve sorumluluklarını, Belirlemektir",
    "category": "Yasal Düzenlemeler",
    "erisimLinki": "https://www.tbmm.gov.tr/kanunlar/kanun-5312"
  },
  {
    "id": "23",
    "kanunNo": "5346",
    "kabulTarihi": "05.10.2005",
    "baslik": "Yenilenebilir Enerji Kaynaklarının Elektrik Enerjisi Üretimi Amaçlı Kullanımına İlişkin Kanun",
    "rgTarih": "18.05.2005",
    "rgSayi": "25819",
    "amac": "Bu Kanunun amacı; yenilenebilir enerji kaynaklarının elektrik enerjisi üretimi amaçlı kullanımının yaygınlaştırılması, bu kaynakların güvenilir, ekonomik ve kaliteli biçimde ekonomiye kazandırılması, kaynak çeşitliliğinin artırılması, sera gazı emisyonlarının azaltılması, atıkların değerlendirilmesi, çevrenin korunması ve bu amaçların gerçekleştirilmesinde ihtiyaç duyulan imalat sektörünün geliştirilmesidir.",
    "category": "Yasal Düzenlemeler",
    "erisimLinki": "https://www.mevzuat.gov.tr/kanun-5346"
  },
  {
    "id": "24",
    "kanunNo": "5686",
    "kabulTarihi": "06.03.2007",
    "baslik": "Jeotermal Kaynaklar Ve Doğal Mineralli Sular Kanunu",
    "rgTarih": "13.06.2007",
    "rgSayi": "26510",
    "amac": "Bu Kanunun amacı, jeotermal ve doğal mineralli su kaynaklarının etkin bir şekilde aranması, araştırılması, geliştirilmesi, üretilmesi, korunması, bu kaynaklar üzerinde hak sahibi olunması ve hakların devredilmesi, çevre ile uyumlu olarak ekonomik şekilde değerlendirilmesi ve terk edilmesi ile ilgili usûl ve esasları düzenlemektir.",
    "category": "Yasal Düzenlemeler",
    "erisimLinki": "https://kutuphane.tarimorman.gov.tr/kanun-5686"
  },
  {
    "id": "25",
    "kanunNo": "5627",
    "kabulTarihi": "18.04.2007",
    "baslik": "Enerji Verimliliği Kanunu",
    "rgTarih": "02.05.2007",
    "rgSayi": "26551",
    "amac": "Bu Kanunun amacı; enerjinin etkin kullanılması, israfının önlenmesi, enerji maliyetlerinin ekonomi üzerindeki yükünün hafifletilmesi ve çevrenin korunması için enerji kaynaklarının ve enerjinin kullanımında verimliliğin artırılmasıdır.",
    "category": "Yasal Düzenlemeler",
    "erisimLinki": "https://kutuphane.sbb.gov.tr/kanun-5627"
  },
  {
    "id": "26",
    "kanunNo": "5710",
    "kabulTarihi": "11.09.2007",
    "baslik": "Nükleer Güç Santrallarının Kurulması Ve İşletilmesi İle Enerji Satışına İlişkin Kanun",
    "rgTarih": "21.11.2007",
    "rgSayi": "26707",
    "amac": "Bu Kanunun amacı; enerji plan ve politikalarına uygun biçimde, elektrik enerjisi üretimi gerçekleştirecek nükleer güç santrallarının kurulması, işletilmesi ve enerji satışına ilişkin usul ve esasları belirlemektir.",
    "category": "Yasal Düzenlemeler",
    "erisimLinki": "https://www.resmigazete.gov.tr/kanun-5710"
  },
  {
    "id": "27",
    "kanunNo": "5836",
    "kabulTarihi": "02.05.2009",
    "baslik": "Kyoto Protokolüne Katılmanın Onaylanmasının Uygun Bulunduğuna Dair Kanun",
    "rgTarih": "17.02.2009",
    "rgSayi": "27144",
    "amac": "5/2/2009 tarihli ve 5836 sayılı Kanunla katılmamız uygun bulunan ekli “Birleşmiş Milletler İklim Değişikliği Çerçeve Sözleşmesine Yönelik Kyoto Protokolü”ne katılmamız; Dışişleri Bakanlığının 7/5/2009 tarihli ve HUMŞ/408 sayılı yazısı üzerine, 31/5/1963 tarihli ve 244 sayılı Kanunun 3 üncü maddesine göre, Bakanlar Kurulu’nca 7/5/2009 tarihinde kararlaştırılmıştır.",
    "category": "Yasal Düzenlemeler",
    "erisimLinki": "https://www.tbmm.gov.tr/kanunlar/kanun-5836"
  },
  {
    "id": "28",
    "kanunNo": "6408",
    "kabulTarihi": "22.01.2013",
    "baslik": "Elektrik Piyasası Kanunu İle Özel Tüketim Vergisi Kanununda Değişiklik Yapılmasına Dair Kanun",
    "rgTarih": "31.01.2013",
    "rgSayi": "28545",
    "amac": "20/2/2001 tarihli ve 4628 sayılı Elektrik Piyasası Kanununun 3 üncü maddesinin birinci fıkrasının (c) bendinin (3) numaralı alt bendinin sonuna aşağıdaki cümle eklenmiştir. “Dağıtım ve perakende satış faaliyetlerinin ayrıştırılması işlemleri, bu Kanuna istinaden belirlenen usul ve esaslar dâhilinde, kayıtlı değerler üzerinden yapılması şartıyla, 5520 sayılı Kurumlar Vergisi Kanunu kapsamında yapılan bölünme işlemi sayılır.”",
    "category": "Yasal Düzenlemeler",
    "erisimLinki": "https://www.mevzuat.gov.tr/kanun-6408"
  },
  {
    "id": "29",
    "kanunNo": "6446",
    "kabulTarihi": "14.03.2013",
    "baslik": "Elektrik Piyasası Kanunu",
    "rgTarih": "30.03.2013",
    "rgSayi": "28603",
    "amac": "Bu Kanunun amacı; elektriğin yeterli, kaliteli, sürekli, düşük maliyetli ve çevreyle uyumlu bir şekilde tüketicilerin kullanımına sunulması için, rekabet ortamında özel hukuk hükümlerine göre faaliyet gösteren, mali açıdan güçlü, istikrarlı ve şeffaf bir elektrik enerjisi piyasasının oluşturulması ve bu piyasada bağımsız bir düzenleme ve denetimin yapılmasının sağlanmasıdır.",
    "category": "Yasal Düzenlemeler",
    "erisimLinki": "https://kutuphane.tarimorman.gov.tr/kanun-6446"
  },
  {
    "id": "30",
    "kanunNo": "6491",
    "kabulTarihi": "30.05.2013",
    "baslik": "Türk Petrol Kanunu",
    "rgTarih": "11.06.2013",
    "rgSayi": "28674",
    "amac": "Bu Kanunun amacı, Türkiye Cumhuriyeti petrol kaynaklarının millî menfaatlere uygun olarak hızlı, sürekli ve etkili bir şekilde aranmasını, geliştirilmesini ve üretilmesini sağlamaktır.",
    "category": "Yasal Düzenlemeler",
    "erisimLinki": "https://kutuphane.sbb.gov.tr/kanun-6491"
  },
  {
    "id": "31",
    "kanunNo": "6765",
    "kabulTarihi": "12.02.2016",
    "baslik": "Türkiye Ve Rusya Arasında Türkakım Gaz Boru Hattı Anlaşmasının Onaylanmasının Uygun Bulunduğuna Dair Kanun",
    "rgTarih": "12.06.2009",
    "rgSayi": "29910",
    "amac": "10 Ekim 2016 tarihinde İstanbul’da imzalanan “Türkiye Cumhuriyeti Hükümeti ve Rusya Federasyonu Hükümeti Arasında TürkAkım Gaz Boru Hattı Projesi’ne İlişkin Anlaşma”nın onaylanması uygun bulunmuştur.",
    "category": "Yasal Düzenlemeler",
    "erisimLinki": "https://www.resmigazete.gov.tr/kanun-6765"
  },
  {
    "id": "32",
    "kanunNo": "7335",
    "kabulTarihi": "10.06.2021",
    "baslik": "Paris Anlaşmasının Onaylanmasının Uygun Bulunduğuna Dair Kanun",
    "rgTarih": "10.07.2021",
    "rgSayi": "31621",
    "amac": "Birleşmiş Milletler İklim Değişikliği Çerçeve Sözleşmesinin 21 inci Taraflar Konferansında kabul edilen ve Türkiye Cumhuriyeti adına 22 Nisan 2016 talihinde imzalanan “Paris Anlaşması”nın beyan ile birlikte onaylanması uygun bulunmuştur.",
    "category": "Yasal Düzenlemeler",
    "erisimLinki": "https://www.tbmm.gov.tr/kanunlar/kanun-7335"
  },
  {
    "id": "33",
    "kanunNo": "7381",
    "kabulTarihi": "03.05.2022",
    "baslik": "Nükleer Düzenleme Kanunu",
    "rgTarih": "08.03.2022",
    "rgSayi": "31772",
    "amac": "Bu Kanunun amacı, barışçıl kullanım ilkesi esas alınarak, nükleer enerji ve iyonlaştırıcı radyasyona ilişkin faaliyetlerin yürütülmesi sırasında çalışanların, halkın, çevrenin ve gelecek nesillerin iyonlaştırıcı radyasyonun olası zararlı etkilerinden korunmasına yönelik uygulanması gereken ilke ve esaslar ile tarafların sorumluluklarını, bu faaliyetler üzerinde düzenleyici kontrol yetkisini haiz Nükleer Düzenleme Kurumunun yetki ve sorumluluklarını ve nükleer hadiselerden kaynaklanan nükleer zararlar hakkındaki hukuki sorumluluğu belirlemektir",
    "category": "Yasal Düzenlemeler",
    "erisimLinki": "https://www.mevzuat.gov.tr/kanun-7381"
  },
  {
    "id": "34",
    "kanunNo": "7429",
    "kabulTarihi": "22.12.2022",
    "baslik": "Elektrik Piyasası Kanunu İle Bazı Kanunlarda Ve 375 Sayılı Kanun Hükmünde Kararnamede Değişiklik Yapılmasına Dair Kanun",
    "rgTarih": "28.12.2022",
    "rgSayi": "32057",
    "amac": "24/11/1994 tarihli ve 4046 sayılı Özelleştirme Uygulamaları Hakkında Kanuna aşağıdaki geçici madde eklenmiştir.",
    "category": "Yasal Düzenlemeler",
    "erisimLinki": "https://kutuphane.tarimorman.gov.tr/kanun-7429"
  },
  {
    "id": "35",
    "kanunNo": "7552",
    "kabulTarihi": "2.7.2025",
    "baslik": "İklim Kanunu",
    "rgTarih": "2025-07-09 00:00:00",
    "rgSayi": "32951",
    "amac": "Bu Kanunun amacı; yeşil büyüme vizyonu ve net sıfır emisyon hedefi doğrultusunda iklim değişikliğiyle mücadele etmektir.",
    "category": "Yasal Düzenlemeler",
    "erisimLinki": "https://kutuphane.sbb.gov.tr/kanun-7552"
  }
];